//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRetailers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentReview
    {
        public int CommentReviewID { get; set; }
        public Nullable<int> CommentID { get; set; }
        public Nullable<int> CommentUserID { get; set; }
        public string ReviewContent { get; set; }
        public Nullable<System.DateTime> ReviewCommentTime { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
