//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRetailers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.Comment = new HashSet<Comment>();
            this.ShoppingCart = new HashSet<ShoppingCart>();
        }
    
        public int GoodsID { get; set; }
        public string GoodsTitle { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string GoodsKeyWord { get; set; }
        public string GoodsAttribute { get; set; }
        public string GoodsImg { get; set; }
        public decimal GoodsPrice { get; set; }
        public int GoodsStock { get; set; }
        public Nullable<int> GoodsSales { get; set; }
        public Nullable<int> GoodsStatu { get; set; }
        public Nullable<System.DateTime> ProductCreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Store Store { get; set; }
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }
    }
}
