//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRetailers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShoppingCart()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int CartID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> GoodsID { get; set; }
        public string SelectAttributes { get; set; }
        public Nullable<int> IsSelect { get; set; }
        public int ProductNum { get; set; }
        public Nullable<int> IsOrder { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual Goods Goods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
