//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRetailers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.Goods = new HashSet<Goods>();
        }
    
        public int StoreID { get; set; }
        public Nullable<int> BusinessID { get; set; }
        public string StoreName { get; set; }
        public string StoreDetails { get; set; }
        public string StoreImg { get; set; }
        public string StoreRegion { get; set; }
        public Nullable<int> StoreScore { get; set; }
        public Nullable<int> StoreHot { get; set; }
        public Nullable<System.DateTime> StoreCreateTime { get; set; }
    
        public virtual Business Business { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Goods> Goods { get; set; }
    }
}
